version: '2'
services:
  corrente-postgresql:
    extends:
      file: postgresql.yml
      service: corrente-postgresql
  corrente-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: corrente-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
  corrente-prometheus:
    extends:
      file: monitoring-localhost.yml
      service: corrente-prometheus
  corrente-grafana:
    extends:
      file: monitoring-localhost.yml
      service: corrente-grafana
