version: '2'
services:
  better-postgresql:
    extends:
      file: postgresql.yml
      service: better-postgresql
  better-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: better-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
  better-prometheus:
    extends:
      file: monitoring-localhost.yml
      service: better-prometheus
  better-grafana:
    extends:
      file: monitoring-localhost.yml
      service: better-grafana
